### ISSUE TITLE
Inliners, outliners

### ISSUE THREAD

**Issue by AlexandrGraschenkov** [srinath1905/GRANSAC#4]
<img width="361" alt="2018-04-12 12 20 03" src="https://user-images.githubusercontent.com/964601/38668124-125dc83a-3e4c-11e8-89b7-8dec0f8f6a41.png">
On your screenshot the black dot also visible near line below green one. Maybe there some error in code.
<br><br>
<i>In my opinion simple example without generic types may have more profit for understanding and usage. There much more code in model, that in GRANSAC.h. It's not bad, but start thinking do we really need this abstraction with templates.</i>

**Comment by drsrinathsridhar** [comment]
Thanks for noticing this. This indeed seems like a bug, I will take a look.

About your second comment: that's the trade-off you have to make when you want a generic implementation. The models can often be more complex than the actual RANSAC code. You can very well write problem specific RANSAC code in far fewer lines if you wish.

**Comment by drsrinathsridhar** [comment]
Hi there,

I fixed a minor bug that was causing the black inlier point to be labeled as an outlier.

Briefly, this was because I was not appending the points used for line model computation to the best inliers. This means that 2 inliers (but not more) were being labeled as outliers. This is fixed now.
